/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_imperial_lsds_saber_devices_TheCPU */

#ifndef _Included_uk_ac_imperial_lsds_saber_devices_TheCPU
#define _Included_uk_ac_imperial_lsds_saber_devices_TheCPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    getNumCores
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_getNumCores
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    bind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_bind
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    unbind
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_unbind
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    getCpuId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_getCpuId
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    optimisedDistinct
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JJJJIIIILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_optimisedDistinct
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jlong, jlong, jlong, jlong, jint, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
