/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_imperial_lsds_saber_devices_TheGPU */

#ifndef _Included_uk_ac_imperial_lsds_saber_devices_TheGPU
#define _Included_uk_ac_imperial_lsds_saber_devices_TheGPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    free
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_free
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    getQuery
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_getQuery
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    setInput
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_setInput
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    setOutput
 * Signature: (IIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_setOutput
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    setKernelDummy
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_setKernelDummy
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    setKernelProject
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_setKernelProject
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    setKernelSelect
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_setKernelSelect
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    setKernelThetaJoin
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_setKernelThetaJoin
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    setKernelReduce
 * Signature: (I[I[J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_setKernelReduce
  (JNIEnv *, jobject, jint, jintArray, jlongArray);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    setKernelAggregate
 * Signature: (I[I[J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_setKernelAggregate
  (JNIEnv *, jobject, jint, jintArray, jlongArray);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    execute
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_execute
  (JNIEnv *, jobject, jint, jintArray, jintArray);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    executeReduce
 * Signature: (I[I[I[J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_executeReduce
  (JNIEnv *, jobject, jint, jintArray, jintArray, jlongArray);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheGPU
 * Method:    executeAggregate
 * Signature: (I[I[I[J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheGPU_executeAggregate
  (JNIEnv *, jobject, jint, jintArray, jintArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
