/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_imperial_lsds_saber_devices_TheCPU */

#ifndef _Included_uk_ac_imperial_lsds_saber_devices_TheCPU
#define _Included_uk_ac_imperial_lsds_saber_devices_TheCPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    getNumCores
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_getNumCores
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    bind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_bind
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    unbind
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_unbind
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    getCpuId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_getCpuId
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    init_clock
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_init_1clock
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    optimisedDistinct
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JJJJIIIILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_optimisedDistinct
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jlong, jlong, jlong, jlong, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    optimisedAggregateHashTables
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIIIIIIIZLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_optimisedAggregateHashTables
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jboolean, jobject, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    changeTimestamps
 * Signature: (Ljava/nio/ByteBuffer;IIIJ)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_changeTimestamps
  (JNIEnv *, jobject, jobject, jint, jint, jint, jlong);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    singleOperatorComputation
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JIIIILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_singleOperatorComputation
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     uk_ac_imperial_lsds_saber_devices_TheCPU
 * Method:    getIntermediateTupleSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_saber_devices_TheCPU_getIntermediateTupleSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
